[package]
name = "grpc-sample"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
tonic = "0.5"
prost = "0.7"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
tonic-build = "0.5"